#!/bin/bash

CONFDIR=/usr/lib/sddm/sddm.conf.d
CONFFILE=80-lliurex.conf
LLIUWIN_USER=lliuwin
LLIUWIN_SESSION=plasma
AUTOSTART=lliuwin-wizard.desktop
set -e
case "$1" in
   remove|purge)
		rm  -f /home/${LLIUWIN_USER}/.config/autostart/$AUTOSTART || echo ""
		#Modify sddm.conf
		WRKFILE=${CONFDIR}/${CONFFILE}
		sed -i "s/User=${LLIUWIN_USER}/#User=/g" $WRKFILE 
		#Disable X11 session
		sed -i "s/Session=${LLIUWIN_SESSION}/#Session=/g" $WRKFILE 
	;;
esac
exit 0
